force-app/main/default/objects/Purchase_Product__c/Purchase_Product__c.object-meta.xml
<CustomObject>
    <label>Purchase Product</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Purchase No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Products</relationshipLabel>
    <relationshipName>Purchase_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Product__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <label>Purchase</label>
    <referenceTo>Purches__c</referenceTo>
    <relationshipLabel>Purchase Products</relationshipLabel>
    <relationshipName>Purchase_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purches__c/Purches__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Purchase No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purches__c/fields/Materials__c.field-meta.xml
<CustomField>
    <fullName>Materials__c</fullName>
    <label>Materials</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raw Material</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purches__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchases</relationshipLabel>
    <relationshipName>Purchases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PurchaseHandlerTest.cls
@isTest
public class PurchaseHandlerTest {
    
    @isTest
    static void testInsertacc() {
        // Create a test Supplier record
        Account testSupplier = new Account(Name = 'Test Supplier',RecordTypeId =System.Label.PurchaseRecordTypeId);
        Product2 testPro = new Product2(Name ='Test Product');
       
        insert testSupplier;
        insert testPro;
        
        
        // Use the ID of the test Supplier
        String supplierId = testSupplier.Id;
        String productId = testPro.Id;
        
        // Create test data
        String apexmaterial = 'Raw Material';
        
        // Create a Purchase_Product__c record (replace with actual field values)
        Purchase_Product__c testProduct = new Purchase_Product__c(Product__c=productId);
        
        // Set testProduct field values here
        
        
        List<Purchase_Product__c> productList = new List<Purchase_Product__c>();
        productList.add(testProduct);
        
        
        // Start test
        Test.startTest();
        
        // Call the method you want to test
        Id purchaseId = PurchaseHandler.insertacc(supplierId, apexmaterial, productList);
        
        // Query the Purches__c and related Purchase_Product__c records to verify the insert
        
        List<Purches__c> insertedProducts = [SELECT Id,Name, Supplier__c, Materials__c ,(SELECT Id,Name, Purchase__c, Product__c FROM Purchase_Products__r) FROM Purches__c WHERE Id = :purchaseId];
        
        // Assertions to verify that the records were inserted correctly
        System.assertEquals(1, insertedProducts.size(), 'One Purchase_Product__c record should be inserted');
        System.assertEquals(supplierId, insertedProducts[0].Supplier__c, 'Supplier Id should match');
        System.assertEquals(apexmaterial,insertedProducts[0].Materials__c, 'Material name should match');
        
        // End test
        Test.stopTest();
    }
}

/*@isTest
public class PurchaseHandlerTest {

@isTest
static void testInsertacc() {
// Create a test Supplier record
Account testSupplier = new Account(Name = 'Test Supplier',RecordTypeId ='0121m000001VmboAAC');
insert testSupplier;

// Use the ID of the test Supplier
String supplierId = testSupplier.Id;

// Create test data
String apexmaterial = 'Raw Material';




// Create a Purchase_Product__c record (replace with actual field values)
Purchase_Product__c testProduct = new Purchase_Product__c();

// Set testProduct field values here


List<Purchase_Product__c> productList = new List<Purchase_Product__c>();
productList.add(testProduct);


// Start test
Test.startTest();

// Call the method you want to test
Id purchaseId = PurchaseHandler.insertacc(supplierId, apexmaterial, productList);

// Query the Purches__c and related Purchase_Product__c records to verify the insert

List<Purches__c> insertedProducts = [SELECT Id, Supplier__c, Materials__c ,(SELECT Id, Purchase__c, Product__c FROM Purchase_Products__r) FROM Purches__c WHERE Id = :purchaseId];

// Assertions to verify that the records were inserted correctly
System.assertEquals(1, insertedProducts.size(), 'One Purchase_Product__c record should be inserted');
System.assertEquals(supplierId, insertedProducts[0].Supplier__c, 'Supplier Id should match');
System.assertEquals(apexmaterial,insertedProducts[0].Materials__c, 'Material name should match');

// End test
Test.stopTest();

}


}*/