force-app/main/default/objects/Minutes_of_Meeting__c/Minutes_of_Meeting__c.object-meta.xml
<CustomObject>
    <label>Minutes of Meeting</label>
    <nameField>
        <displayFormat>MOM-{0000}</displayFormat>
        <label>Minutes of Meeting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minutes of Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Minutes of Meetings</relationshipLabel>
    <relationshipName>Minutes_of_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Minutes of Meetings</relationshipLabel>
    <relationshipName>Minutes_of_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Minutes of Meetings</relationshipLabel>
    <relationshipName>Minutes_of_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Meeting_Notes__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Notes__c</fullName>
    <label>Meeting Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Google Meet</fullName>
            </value>
            <value>
                <fullName>Microsoft teams</fullName>
            </value>
            <value>
                <fullName>zoom</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/MOM_Date__c.field-meta.xml
<CustomField>
    <fullName>MOM_Date__c</fullName>
    <label>MOM Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Minutes of Meetings</relationshipLabel>
    <relationshipName>Minutes_of_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Minutes of Meetings</relationshipLabel>
    <relationshipName>Minutes_of_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Meeting__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Minutes_of_Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Minutes_of_Metting_Description__c/Minutes_of_Metting_Description__c.object-meta.xml
<CustomObject>
    <label>Minutes of Meetting Description</label>
    <nameField>
        <displayFormat>MOMD-{0000}</displayFormat>
        <label>Minutes of Metting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minutes of Meettings Description</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Minutes_of_Metting_Description__c/fields/Minutes_of_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Minutes_of_Meeting__c</fullName>
    <label>Minutes of Meeting</label>
    <referenceTo>Minutes_of_Meeting__c</referenceTo>
    <relationshipLabel>Minutes of Meettings Description</relationshipLabel>
    <relationshipName>Minutes_of_Meettings_Description</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MinutesofMeetinghandler.cls
public class MinutesofMeetinghandler {
    @AuraEnabled
    public static id insertpdd(date apexdate,string apexsubject,string apexmeetingnote,string meetingtype,string apexremark,string apexaccount,string apexcontact,string apexopportunity,string apexlead,string apexproject,string apexuser , list<Minutes_of_Metting_Description__c> MinutesofMettings){
        
        Minutes_of_Meeting__c Mom=new Minutes_of_Meeting__c();
        Mom.MOM_Date__c =apexdate;
        Mom.Subject__c = apexsubject;
        Mom.Meeting_Notes__c=String.isBlank(apexmeetingnote) ? null : apexmeetingnote;
        Mom.Meeting_Type__c=String.isBlank(meetingtype) ? null : meetingtype;
        Mom.Remarks__c=String.isBlank(apexremark) ? null : apexremark;
        Mom.Account__c=String.isBlank(apexaccount) ? null : apexaccount;
        Mom.Contact__c=String.isBlank(apexcontact) ? null : apexcontact; 
        Mom.Opportunity__c=String.isBlank(apexopportunity) ? null : apexopportunity;
        Mom.Lead__c=String.isBlank(apexlead) ? null : apexlead;
        Mom.Project__c=String.isBlank(apexproject) ? null : apexproject;
        Mom.User__c=String.isBlank(apexuser) ? null : apexuser;
   
        insert Mom;
        
        system.debug('Minutes of Meeting insert'+Mom);
        
        
        for (Minutes_of_Metting_Description__c momdes : MinutesofMettings) {
            system.debug(MinutesofMettings);
            momdes.Minutes_of_Meeting__c = Mom.id;
        }
        insert MinutesofMettings;
        system.debug(MinutesofMettings);
        return Mom.id;
        
    }
}