force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/Sample_Request__c.object-meta.xml
<CustomObject>
    <label>Sample Request</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sample Request</relationshipLabel>
    <relationshipName>Sample_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Batch_No__c</fullName>
    <label>Batch No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Customer_Agent_Request_Letter_Enclosed__c.field-meta.xml
<CustomField>
    <fullName>Customer_Agent_Request_Letter_Enclosed__c</fullName>
    <label>Customer/Agent Request Letter Enclosed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Customer_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Customer_Request_Date__c</fullName>
    <label>Customer Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Customer_Specifications_Enclosed__c.field-meta.xml
<CustomField>
    <fullName>Customer_Specifications_Enclosed__c</fullName>
    <label>Customer Specifications Enclosed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sample Request</relationshipLabel>
    <relationshipName>Sample_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Packaging_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Requirement__c</fullName>
    <label>Packaging Requirement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sample Request</relationshipLabel>
    <relationshipName>Sample_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Sample Request</relationshipLabel>
    <relationshipName>Sample_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Sample_Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sample_Sr_No__c</fullName>
    <displayFormat>SN-{0000}</displayFormat>
    <label>Sample Sr.No.</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Samples__c.field-meta.xml
<CustomField>
    <fullName>Samples__c</fullName>
    <label>Samples</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market Sample</fullName>
            </value>
            <value>
                <fullName>Working Standard Sample</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submitted to Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Request__c/fields/Supporting_Documents_Required__c.field-meta.xml
<CustomField>
    <fullName>Supporting_Documents_Required__c</fullName>
    <label>Supporting Documents Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>b</fullName>
            </value>
            <value>
                <fullName>c</fullName>
            </value>
            <value>
                <fullName>d</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SampleRequestPDFController.cls
public class SampleRequestPDFController {
    public Id recordId {get; set;}
    public List<Sample_Request__c> sam { get; set; }
    
  
    public SampleRequestPDFController(ApexPages.StandardController controller) {
        
        recordId = ApexPages.currentPage().getParameters().get('id');
        system.debug('id=='+recordId);
        
        sam = [SELECT Id,Sample_Sr_No__c,Batch_No__c,CreatedDate,Owner.Name,Customer_Agent_Request_Letter_Enclosed__c,Name,Dispatch_Date__c, Account_Name__r.Name,Opportunity__r.Name,Project__r.Name,Product_Name__r.Name,Samples__c,Quantity__c,Customer_Specifications_Enclosed__c,Packaging_Requirement__c,Supporting_Documents_Required__c,Customer_Request_Date__c,Status__c, Email__c FROM Sample_Request__c where id=:recordId];
        
        
    }
    public PageReference pdf() {
        if (sam.isEmpty()) {
             // return null;No complaint to generate PDF
        }
        Sample_Request__c SA = sam[0];
        
        PageReference pdfPage = Page.SampleRequestPDF;
        pdfPage.getParameters().put('id', SA.Id);
        blob pdfBlob;
                   
            if(Test.isRunningTest())
            {
            pdfBlob = blob.valueOf('Unit.Test'); }
            else
            {
            pdfBlob = pdfPage.getContentAsPDF();
            }
       return null;
    }
    
}